appName: FindFalsePositves
logLevel: WARN

BigID:
    report_file: Objects.csv
    classifiers:
      SSN: (?<![\-\$\.@])(?!(\d)\1{2}\1{2}\1{4})\b(?:0(?:0[1-9]|[1-9]\d)|[1-578]\d{2}|6(?:[0-57-9]\d|6[0-57-9]))()(?:0[1-9]|[1-9]\d)\2(?:0(?:0(?:0[1-9]|[1-9]\d)|[1-9]\d{2})|[1-9]\d{3})\b(?![\-‐‑‒–—―@$]|\.\d)(?<!(?:123456789)|987654321)
      credit_card: (?<!\w|\-|@|\.)(?:[3-6])(?:(?:\d{13,15})|(?:\d{2}([ -])\d{5}\1\d{5}\1\d{3})|(?:\d{3}([ -])\d{4}\2\d{4}\2\d{4})|(?:\d{3}([ -])\d{6}\3\d{5})|(?:\d{5}([ -])\d{6}\4?\d{4}))(?!\w|\-|@|\.)
      driver_licence: (?<![\-‐‑‒–—―\.\$])\b(?:\d{2}(?:(\-)\d{2}(?:\d\1\d{4}|\1\d{5})|\d(?:\d(?:(\-)\d{2}\2\d{4}|\d{2}(?:\d(?:\d(?:\d(?:\d(?:\d{2,3})?)?)?|A)?|\-\d{3}))|[A-Z]{2}\d{4}|( )\d{3}\3\d{3})|[A-Z]{3}\d{5}|( )\d{3}\4\d{3})|[A-Z](?:[A-Z](?:[A-Z](?:(\-)\d{2}\5\d{4}|\d{6}|[A-Z\*]{2}[A-Z][A-Z\*]\d{3}[B-DJ-U1-9][A-HJ-NP-UWZ\d])|\d{6}[A-Z]?|\*{3}[A-Z][A-Z\*]\d{3}[B-DJ-U1-9][A-HJ-NP-UWZ\d])|\d{2}(?:\d(?:\d(?:\d{2}(?:\d(?:\d(?:\d(?:\d{2}(?:\d(?:\d{1,2})?)?)?)?)?)?|( )\d{5}\6\d{5})|(\-)\d{3}(?:\d\7\d{4}(?:\7\d{2})?|\7\d{2}(?:\d\7\d{3}|\7\d{3}\7\d)))|(\-)\d{3}\8\d{3})|(\-)\d{3}\9\d{3}\9\d{3}\9\d{3}|( )\d{3}\10\d{3}\10\d{3}\10\d{3})|K\d{2}(\-)\d{2}\11\d{4}|V\d{6}|WDL[B-DF-HJ-NPR-TW-Z\d]{9})\b(?![\-‐‑‒–—―\$]|\.\d)
scan_files:
  pagination:
    offset: 0
    limit: -1
    page_size: 10
  output_file: matches_samples.json

