appName: FindFalsePositves
logLevel: WARN

BigID:
    report_file: Objects.csv
    data_source_type: s3
    classifiers:
      SSN: (?<![\-\$\.@])(?!(\d)\1{2}\1{2}\1{4})\b(?:0(?:0[1-9]|[1-9]\d)|[1-578]\d{2}|6(?:[0-57-9]\d|6[0-57-9]))()(?:0[1-9]|[1-9]\d)\2(?:0(?:0(?:0[1-9]|[1-9]\d)|[1-9]\d{2})|[1-9]\d{3})\b(?![\-‐‑‒–—―@$]|\.\d)(?<!(?:123456789)|987654321)
      credit_card: (?<!\w|\-|@|\.)(?:[3-6])(?:(?:\d{13,15})|(?:\d{2}([ -])\d{5}\1\d{5}\1\d{3})|(?:\d{3}([ -])\d{4}\2\d{4}\2\d{4})|(?:\d{3}([ -])\d{6}\3\d{5})|(?:\d{5}([ -])\d{6}\4?\d{4}))(?!\w|\-|@|\.)
      SSN-hyphen: (?<![\-\$\.@])(?!(\d)\1{2}[ \t\-‐‑‒–—―\uff0d ]\1{2}[ \t\-‐‑‒–—―\uff0d ]\1{4})\b(?:0(?:0[1-9]|[1-9]\d)|[1-578]\d{2}|6(?:[0-57-9]\d|6[0-57-9]))([ \t\-‐‑‒–—―\uff0d ])(?:0[1-9]|[1-9]\d)\2(?:0(?:0(?:0[1-9]|[1-9]\d)|[1-9]\d{2})|[1-9]\d{3})\b(?![\-‐‑‒–—―@$]|\.\d)(?<!(?:123[ \t\-‐‑‒–—―\uff0d ]45[ \t\-‐‑‒–—―\uff0d ]6789)|987[ \t\-‐‑‒–—―\uff0d ]65[ \t\-‐‑‒–—―\uff0d ]4321)
scan_files:
  pagination:
    offset: 0
    limit: -1
    page_size: 5
  output_file: secure_risk.json
  fail_over: true
SMB_connection:
  attempts: 5
S3_connection:
  max_file_size: 536870912


